services:
  db:
    image: postgres:16-alpine
    container_name: tirta_asri_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: tirta
      POSTGRES_PASSWORD: tirta123
      POSTGRES_DB: tirta_asri
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
