import { Poppins, Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar";
import 'remixicon/fonts/remixicon.css';

const fontPoppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

const fontPlayfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['500', '600'],
  variable: '--font-playfair',
});

export const metadata = {
  title: "Tirta Asri Website",
  description: "Generated by Damar Alam",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontPoppins.className} ${fontPlayfair.variable} antialiased`}>
        <Navbar />
        <div className="container mx-auto px-4">{children}</div>
      </body>
    </html>
  );
}